### ISSUE TITLE
404 (Not Found) in Github actions

### ISSUE THREAD

**Issue by 2Dennis** [ajinx/zalenium#2]
```
name: Frontend-testing
on:
  push:
    branches: [ master ]
    
jobs:
  start-zalenium:
    runs-on: ubuntu-latest
    name: ZALENIUM JOB
    steps:
    - uses: actions/checkout@v2
    - uses: ajinx/zalenium@v1.1
    - run: npm ci    
    - name: start zalenium
      uses: ./
    - name: is zalenium started?
      run: curl http://localhost:4444/status
```
**ajinx/zalenium@v1.0** and **ajinx/zalenium@v1.1** are resulting in a 404 error: 

> Failed to download action 'https://api.github.com/repos/ajinx/zalenium/tarball/v1.1'. Error Response status code does not indicate success: 404 (Not Found).

**Comment by ajinx** [comment]
@2Dennis Can you retest it and verify that under your repo settings > actions Enable local and third party Actions for this repository is enabled ? 

I retested it and it seems to be working at my end. Any log snippet would be lot useful to further investigate it.

**Comment by 2Dennis** [comment]
@ajinx many thanks for your response! I retested this again and it failed again. 

**Important**: **ajinx/selenoid@2.0** is working without any issues and I have "_Enable local and third party Actions for this repository_" enabled.

 **ajinx/zalenium@v1.1**
`Current runner version: '2.169.0'
Operating System
  Ubuntu
  18.04.4
  LTS
Virtual Environment
  Environment: ubuntu-18.04
  Version: 20200406.2
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20200406.2/images/linux/Ubuntu1804-README.md
Prepare workflow directory
Prepare all required actions
Download action repository 'actions/checkout@v2'
Download action repository 'ajinx/zalenium@v1.1'
##[warning]Failed to download action 'https://api.github.com/repos/ajinx/zalenium/tarball/v1.1'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 19.089 seconds before retry.
##[warning]Failed to download action 'https://api.github.com/repos/ajinx/zalenium/tarball/v1.1'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 22.48 seconds before retry.
##[error]Response status code does not indicate success: 404 (Not Found).`

 **ajinx/selenoid@2.0**
```
100 12.5M  100 12.5M    0     0  36.9M      0 --:--:-- --:--:-- --:--:-- 72.6M
Run ajinx/selenoid@2.0
## STARTING SELENOID USING CM TOOLS
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   625  100   625    0     0   4032      0 --:--:-- --:--:-- --:--:--  4032

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
## STARTING SELENOID FINISHED
100 12.5M  100 12.5M    0     0  36.9M      0 --:--:-- --:--:-- --:--:-- 72.6M
```

**Comment by ajinx** [comment]
@2Dennis I used an external repo and used below sample snippet to execute my tests on Maven and it did work perfectly fine. Can you modify it based upon your testing tool
```
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run Java CI
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Maven
      uses: stCarolas/setup-maven@v1
    - uses: actions/cache@v1.1.0
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Zalenium Server
      uses: ajinx/zalenium@1.1
    - name: Run test
      env:
        SELENIUM_HUB_HOST: 'localhost'
      run: mvn verify

```
Can you update above snippet as per your need and try it accordingly?

Let me know if it didn't worked out?

In case of authentication issues, Name mismatch, Capital letter in repo etc  Github just provides 404 Not found error.

**Comment by ajinx** [comment]
@2Dennis Any updates over it? If not I will close it on monday. Thanks

**Comment by 2Dennis** [comment]
@ajinx it's working again! Your solution and my original workflows are now running. You can close this issue. Thanks for the support!

**Working solution:** 
```
# This workflow will install Selenium & Python dependencies and will run the frontend tests

name: Frontend Testing
on:
  push:
    branches: [ master ]

  # trigger this workflow from a remote repository  
  repository_dispatch:
    branches: [ master ]
    
jobs:
  tests:
    runs-on: ubuntu-latest
    
    env:
      BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
      BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}  
    
    name: Run Java CI
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Maven
      uses: stCarolas/setup-maven@v1
    - uses: actions/cache@v1.1.0
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Zalenium Server
      uses: ajinx/zalenium@1.1
    - name: is selenium started?
      run: curl http://localhost:4444/status
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Frontend tests
      run: |
        python run_tests.py
```
**My workflow**

```
# This workflow will install Selenium & Python dependencies and will run the frontend tests

name: Frontend Testing
on:
  push:
    branches: [ master ]

  # trigger this workflow from a remote repository  
  repository_dispatch:
    branches: [ master ]
    
jobs:
  frontend-testing:
    name: Frontend Testing
    runs-on: ubuntu-latest

    env:
      BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
      BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}    

    steps:
    - uses: actions/checkout@v2
    - uses: ajinx/zalenium@1.1

    - name: is selenium started?
      run: curl http://localhost:4444/status

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Frontend tests
      run: |
        python run_tests.py

```
