### ISSUE TITLE
When attempting to use your action github could not find it.  See error below.

### ISSUE THREAD

**Issue by halleynora** [ajinx/zalenium#3]
##[error]An action could not be found at the URI 'https://api.github.com/repos/ajinx/zalenium/tarball/v1.1'

example of my workflow
    - name: Execute tests on Zalanium grid
      uses: ajinx/zalenium@v1.1
    - uses: actions/checkout@v2
    - run: npm ci
    - name: Test with gradlew
      run: |
        gradle wrapper
        ./gradlew build
        ./gradlew test

**Comment by ajinx** [comment]
Hi @halleynora Can you confirm on following steps

Can you retest it and verify that under your repo settings > actions Enable local and third party Actions for this repository is enabled ?

In case of authentication issues, Name mismatch, Capital letter in repo etc Github just provides 404 Not found error.

Can you re run your workflow with

```
- uses: actions/checkout@v2
- name: Execute tests on Zalanium grid
  uses: ajinx/zalenium@v1.1
- name: Test with gradlew
  run: |
      gradle wrapper
      ./gradlew build
      ./gradlew test
```

**Comment by ajinx** [comment]
Another example, Here replace maven with gradle 

```
- name: Zalenium Server
   uses: ajinx/zalenium@1.1
- name: Run test
   env:
        SELENIUM_HUB_HOST: 'localhost'
   run: mvn verify
```
